# Generated by Django 3.0.9 on 2020-08-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200819_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Отметьте книгу как возвращенную'),)},
        ),
    ]
